# Generated by Django 3.2.13 on 2022-10-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.CharField(choices=[('1', 'BLUE'), ('2', 'RED')], max_length=10),
        ),
    ]
