SELECT 
    INFO.REST_ID
    , INFO.REST_NAME
    , INFO.FOOD_TYPE
    , INFO.FAVORITES
    , INFO.ADDRESS
    , SCORE_BY_REST.SCORE
FROM
    REST_INFO INFO
    , (
        SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) SCORE 
        FROM REST_REVIEW
        GROUP BY REST_ID
    ) SCORE_BY_REST
WHERE 
    INFO.REST_ID = SCORE_BY_REST.REST_ID
    and ADDRESS LIKE '서울%'
ORDER BY
    SCORE_BY_REST.SCORE DESC
    , INFO.FAVORITES DESC
;